### PR TITLE
Color Customization & Changed Colors

### PR DESCRIPTION
**Pull request by davewiththenicehat**
Changed most colors within the client. Intention is to reduce eye strain.
Created ability to customize colors thoroughout the client.
Created bugfix for old exit highlighting standard.
Rumors now go to the communications window.

### CODE REVIEW

**Comment by davewiththenicehat** [comment]
John could you check this than merge it for me?
I fixed the bleeding gray text issue with this one. The one that was the old standard, and it causes the text to be dark gray after an exit.

**Comment by johnnymo87** [comment]
Screenshot from 2019-11-02 11-53-51

**Comment by johnnymo87** [comment]
Nice work @davewiththenicehat :trophy: 

Merged.

**Comment by davewiththenicehat** [comment]
Thanks!
This was a fun branch to make.

**Pull request merged**
