### PR TITLE
2d map

### PR DESCRIPTION
**Pull request by davewiththenicehat**
Mostly completed code for drawing the rooms for the TEC map. I still need code the be able to adjust gap between each room. I'd forgotten I wanted that feature available.
Started help command. Intended it to be a how to do it.
created best practices file. will move it to git wiki
created command to clear main display window. Also found and resolved a bug in mudlet. If another window attempts to get mains background. It errors out if main is cleared with no text.
Created debug window. I wound up not only being too much junk on main, but also hinsert has a bug and we can not echo to main inside a trigger.
I will submit a bug report for hinsert. For now we can work around it. If need be we can either fix hinsert ourselves or convert the html hex color codes to RGB
Removed temp login feature to make way for functional login.

### CODE REVIEW

**Comment by johnnymo87** [comment]
@davewiththenicehat I merged Li-Hsuan's branch to master, and that introduced some conflicts with this branch. They seemed very mild, so I resolved them myself, and pushed a commit. On your local machine, make sure you `pull` before doing anything else on this branch, or else you won't have Li-Hsuan's latest changes from master.

**Comment by johnnymo87** [comment]
@davewiththenicehat I'm seeing an issue. It's minor, so maybe it's worth it to merge this anyway, and follow up with a small PR that fixes the bug.

I tried out this code just now, and I noticed something slightly off that I believe was working before our meeting yesterday. I'm seeing that not all the map squares are rendering. The ones that are further away seem to be missing. When I walk towards them, they render.

Checkout what I'm seeing below. These little squares to the east of Constantine don't render when I'm next to him, only when I walk towards them.

Screencast from 09-15-2019 02_33_04 PM

**Comment by davewiththenicehat** [comment]
Actually I had noticed that. It is the same issue that I was seeing where there are exits but the rooms there were pointing to were missing.
Would up being my lua string pattern.
Here is a close up with the pattern fixed and the exits working. Character is standing in the toga inn.
image

**Comment by davewiththenicehat** [comment]
Those angled exits closed icons look like penises. Actually if I look close. The angled exit open icons look like a slightly bent penis.
Should we just wait to merge now that I am nearly done with the entire 2d map? This would be merging bugs that would later be resolved. I should be fully done tomorrow. Well done, but with these real high quality exit icons.

**Comment by davewiththenicehat** [comment]
O also, I think you are getting a smaller map?
Could you do us a favor and not fix your old account so we can see how many issues returning players may run into?

**Comment by davewiththenicehat** [comment]
That is a good enough for our purposes of wanted to get this branch to master.
While it is functional it has a poor appearance. I think I figured out how to give it a finished look. I'll work on that next.

**Review by johnnymo87 — APPROVED** [review]
I gave it a run, and I'm seeing all the rooms again. Nice work, let's merge :+1:

**Pull request merged**
