### PR TITLE
Support macros

### PR DESCRIPTION
**Pull request by johnnymo87**
Screenshot

Screenshot from 2019-09-29 09-26-51

### CODE REVIEW

**Comment by davewiththenicehat** [comment]
That work in progress is looking great. I really like that you made them labels.
I bothered Vadi about margins, borders and padding. With QT they can change the label and position text within the label. They do not assist with positioning child geyser objects.
In the Room Character PR there is a resize function that is easily copied and changed for main windows.
As a heads up you will notice that the bottom of your macro window will get overlapped by the command window after typing in it.
I am creating a fix for it that will be in the settings window PR.
As a reminder all these labels need to do to work is send("fe1") send("fe2").
It is looking great.

**Comment by johnnymo87** [comment]
@davewiththenicehat I think this is ready. I've tested it out, and it works.

I spent a lot of time trying to do marginal improvements to the appearance, got stuck, and went back to the simplest styling possible.

**Comment by davewiththenicehat** [comment]
> @davewiththenicehat I think this is ready. I've tested it out, and it works.
> 
> I spent a lot of time trying to do marginal improvements to the appearance, got stuck, and went back to the simplest styling possible.

I've found the style system a tad lacking also. Did you run into a situation where you would enable a feature and the desired affect just simply did not appear? If I recall I had that issue with border styles. Almost like the setting was not getting passed to QTs draw system...

**Comment by johnnymo87** [comment]
I had the borders working alright (they're the white lines in my screenshot). For me, the issue was that I wanted to set min/max widths/heights on the macro menu, so that it would be resizable within those bounds, and then fixed if the screen was contorted beyond that. But it wasn't really that important, so I let it go.

**Comment by davewiththenicehat** [comment]
That requires creating a resize function. I felt the same way. Was thinking what am I missing. Reviewed a bunch. Finally I ask Vadi about it. He almost seemed perplexed that you would want to have that type of control over the graphical element of a project.
In all I guess it is not bad. Creating the resize functions is not cumbersome. Just surprising that it is required.
Off subject I created a bunch of projects to give us some ideas of what to work in. I put them in the github project section.

**Pull request merged**
