### PR TITLE
tecMap V1 Completed

### PR DESCRIPTION
**Pull request by davewiththenicehat**
Exit icons now properly position themselves.
As the window resizes the tecMap and compass stay square.
Later releases we can create an option to not do this. To me things look a bit off when they are not square.
Created full theme support for the exit icons.
png images were only needed for angled exits. They are in the ims.mpackage file.

### CODE REVIEW

**Review by johnnymo87 — APPROVED** [review]
I'm trying this out on my machine. I've never tried resizing any of the panes, and I think I need to now. Without resizing it, it looks like this for me:

Screenshot from 2019-09-21 11-16-24

I bet if I figured out how to resize these panes, I'd see something a little more proportional, like you shared in the TEC discord:
big-map

My guess is that since the doors are images, they don't resize, and so the default zoom of the map skews things a bit?

Either way, the code looks clean and well-commented, so this is a very nice iteration on the map :clap:

**Comment by davewiththenicehat** [comment]
I see is your screen very low res? Headless VM?

The display can be resized by right clicking the blue arrows.
I was thinking about that today. The game needs to have some kind of intro video that plays on first use.

Any rate.
The exits on an angle are pngs. I can tell them to draw at half height when the full label is 120 or less. Though it will make them thinner. I don't see it as being an issue...
The other exits are labels. I can do what ever I want with them.

**Comment by johnnymo87** [comment]
Low-res? Headless VM? Hmm no, this is just me running ubuntu on a thinkpad laptop. Can you share a screenshot of how it looks for you?
 
_Right_ clicking, ah, that's what I was doing wrong -- I was left clicking. OK, things look much more legible once I expand them a little. I think people will need things a little larger by default, but as you say, maybe a short video will be enough to guide to users to learn how to tune things themselves.

**Comment by davewiththenicehat** [comment]
On later release I would like to create a zoom feature.
When I do I want to see about auto zooming. So the map fills the view-able window.

I am worried about the need to right click to drag the windows. I am relutant to change it to a left click. Because one of them overlaps with mains scroll bar.
I feel if we got the out of the way we could change it to a left click.
What would be great is if we could turn the arrows into a label that was between the tabbed windows on the left and right. If that label just had the look of a drag window people would get it.
However, working inside GUIframe's code is very difficult.

Here's a window as I see it. On startup. Without adjusting any windows.
image

**Pull request merged**
