### PR TITLE
Courses script

### PR DESCRIPTION
**Pull request by davewiththenicehat**
scripts for iridine courses
ability to use the `stop` command to stop scripts in parthia as well as TEC.
bugfix adding special exits when moving through a direction with multiple exits and a door is closed.
command `run courses` to start running a course
help for courses in the `parthia command` help function

### CODE REVIEW

**Comment by davewiththenicehat** [comment]
If I merge this will it cause issues with the branches you merged?

**Comment by PatrickDattilio** [comment]
> If I merge this will it cause issues with the branches you merged?

Yes, they would need to be re-merged or rebased. Can you change this PR to merge into develop instead?

**Comment by PatrickDattilio** [comment]
Actually, I was able to switch it to develop. This should be good to merge now, and potentially enough for a release?

**Comment by davewiththenicehat** [comment]
scripts for iridine courses
ability to use the stop command to stop scripts in parthia as well as TEC.
bugfix adding special exits when moving through a direction with multiple exits and a door is closed.
command run courses to start running a course
help for courses in the parthia command help function

**Pull request merged**
