### PR TITLE
Room characters window

### PR DESCRIPTION
**Pull request by davewiththenicehat**
Resolved issue: https://github.com/TheEternalCitizens/mudlet-integration/issues/29
https://github.com/TheEternalCitizens/mudlet-integration/issues/15

Refer to 
https://github.com/TheEternalCitizens/mudlet-integration/commit/d54f6ccc5480946c830f81671b30e08a43f91d35
https://github.com/TheEternalCitizens/mudlet-integration/commit/736d1ad0c1249b78ef99b3cfcc50db050f13a3ae
for details.

### CODE REVIEW

**Comment by johnnymo87** [comment]
So is room check on by default unless you do something that causes it to turn off, and then you can manually re-enable it?

**Comment by davewiththenicehat** [comment]
> So is room check on by default unless you do something that causes it to turn off, and then you can manually re-enable it?

It has to be run manually. With TEC only being able to accept 1 command a second spamming the system with "ac ." command was causing issues. Especially when walking. It was locking the user out. In large combats commands were having a several second delay.

With v1 it will prompt the user when a refresh is recommended.
It will be possible to automate the list, but requires too much time to release this along with V1.

Refreshing the charater window is currently done with command "ac ." (it still displays the command to screen), pressing ctrl+r, or running command "room check". ctrl+r and "room check" do not show the output of the client running "ac ." to the main console. It is only reflected in the character window.

**Comment by davewiththenicehat** [comment]
O also, this addresses an issue where automated Room Character checks would break a game skill.

**Comment by johnnymo87** [comment]
@davewiththenicehat when I press `ctrl+r`, the character window goes blank and does not show who is in the room.

Screenshot from 2019-11-02 11-42-05

I've copy and pasted below the relevant part of the debug log, in case that helps.
```
LUA OK: script ctrl+r -> Room Check (Key16) ran without errors
new line arrived:</pre><pre><font size=+1><b>Checking the approach status of &quot;.
&quot;</b></font></font>

LUA OK script onNewLine Trigger (trigger2condition0) ran without errors
LUA OK script Room Character Check (trigger36condition0) ran without errors
Trigger name=Room Character Check(return getTECRoomCheckActive()) matched.
LUA OK: script Room Character Check (Trigger36) ran without errors
Trigger name=Text Filters(^) matched.

selectSection(0,26): line under current user cursor: ERROR: invalid line number

selectSection(0,26): line under current user cursor: ERROR: invalid line number
LUA OK: script Text Filters (Trigger39) ran without errors
new line arrived:<hr>

LUA OK script onNewLine Trigger (trigger2condition0) ran without errors
LUA OK script Room Character Check (trigger36condition0) ran without errors
Trigger name=Room Character Check(return getTECRoomCheckActive()) matched.
LUA OK: script Room Character Check (Trigger36) ran without errors
Trigger name=delete lines(<hr>) matched.
LUA OK: script delete lines (Trigger38) ran without errors
Trigger name=Text Filters(^) matched.

selectSection(0,26): line under current user cursor: ERROR: invalid line number

selectSection(0,26): line under current user cursor: ERROR: invalid line number
LUA OK: script Text Filters (Trigger39) ran without errors
new line arrived:1: Phaedra

LUA OK script onNewLine Trigger (trigger2condition0) ran without errors
LUA OK script Room Character Check (trigger36condition0) ran without errors
Trigger name=Room Character Check(return getTECRoomCheckActive()) matched.
LUA OK: script Room Character Check (Trigger36) ran without errors
Trigger name=Text Filters(^) matched.

selectSection(0,26): line under current user cursor: ERROR: invalid line number

selectSection(0,26): line under current user cursor: ERROR: invalid line number
LUA OK: script Text Filters (Trigger39) ran without errors
new line arrived:2: Fralphye

LUA OK script onNewLine Trigger (trigger2condition0) ran without errors
LUA OK script Room Character Check (trigger36condition0) ran without errors
Trigger name=Room Character Check(return getTECRoomCheckActive()) matched.
LUA OK: script Room Character Check (Trigger36) ran without errors
Trigger name=Text Filters(^) matched.

selectSection(0,26): line under current user cursor: ERROR: invalid line number

selectSection(0,26): line under current user cursor: ERROR: invalid line number
LUA OK: script Text Filters (Trigger39) ran without errors
new line arrived:<hr>

LUA OK script onNewLine Trigger (trigger2condition0) ran without errors
LUA OK script Room Character Check (trigger36condition0) ran without errors
Trigger name=Room Character Check(return getTECRoomCheckActive()) matched.
LUA OK: script Room Character Check (Trigger36) ran without errors
Trigger name=delete lines(<hr>) matched.
LUA OK: script delete lines (Trigger38) ran without errors
Trigger name=Text Filters(^) matched.

selectSection(0,26): line under current user cursor: ERROR: invalid line number

selectSection(0,26): line under current user cursor: ERROR: invalid line number
LUA OK: script Text Filters (Trigger39) ran without errors
new line arrived:</pre>

LUA OK script onNewLine Trigger (trigger2condition0) ran without errors
LUA OK script Room Character Check (trigger36condition0) ran without errors
Trigger name=Room Character Check(return getTECRoomCheckActive()) matched.
LUA OK: script Room Character Check (Trigger36) ran without errors
Trigger name=delete lines(</pre>) matched.
LUA OK: script delete lines (Trigger38) ran without errors
Trigger name=Text Filters(^) matched.

selectSection(0,26): line under current user cursor: ERROR: invalid line number

selectSection(0,26): line under current user cursor: ERROR: invalid line number
LUA OK: script Text Filters (Trigger39) ran without errors
```

**Comment by davewiththenicehat** [comment]
selectSection(0,26): line under current user cursor: ERROR: invalid line number annoys the shit out of me know that I see it. However I can tell it is not releted to Room Characters Window. It actually happens inside of Text Filters. I will track that down.
As for the issue, it is working without trouble for me?
Could you also run through the report issues command in the settings window.
Get a debug file for this. I need it because I need to see the issue. Stupid ass thing works for me!
However I am suddenly happy I created the report issues function.

**Comment by davewiththenicehat** [comment]
John, could you double check this before I merge it.
We fixed two bugs on this you had found. The issue with it not displaying, and the issue that some of the refresh checks were not processing.
I know the display fix worked, is there are issues after commit https://github.com/TheEternalCitizens/mudlet-integration/pull/36/commits/a220ed2e2d175fa5803e834c42663d44f261d2fb
That should be the end of this branch until we automated it again, but properly that time...

**Pull request merged**
